export const INITIAL_RECORDS = [
  {
    "id": "excel-0001",
    "fecha": "2026-04-21",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 45,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 21 de abril se verifico la información de las polizas y se actualizaron los datos en fosmarcore, del plan basico",
    "createdAt": "2026-04-21T09:01:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0002",
    "fecha": "2026-04-21",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 6,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 21 de abril se verifico la información de las polizas y se actualizaron los datos en fosmarcore, del plan basico",
    "createdAt": "2026-04-21T09:02:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0003",
    "fecha": "2026-04-21",
    "tipo": "Levantadas",
    "categoria": "Observaciones levantadas",
    "cantidad": 3,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 21 de abril se verifico la información de las polizas y se actualizaron los datos en fosmarcore, del plan basico",
    "createdAt": "2026-04-21T09:03:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "acumulado",
    "campoReporte": "Observaciones levantadas"
  },
  {
    "id": "excel-0004",
    "fecha": "2026-04-22",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 44,
    "grupo": "Primer grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 22  de abril, se verifico la información escrita en los contratos del plan de salud complementario onconaval y se actualizaron los datos en fosmacore.",
    "createdAt": "2026-04-22T09:04:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0005",
    "fecha": "2026-04-22",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 11,
    "grupo": "Primer grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 22  de abril, se verifico la información escrita en los contratos del plan de salud complementario onconaval y se actualizaron los datos en fosmacore.",
    "createdAt": "2026-04-22T09:05:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0006",
    "fecha": "2026-04-22",
    "tipo": "Levantadas",
    "categoria": "Observaciones levantadas",
    "cantidad": 10,
    "grupo": "Primer grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 22  de abril, se verifico la información escrita en los contratos del plan de salud complementario onconaval y se actualizaron los datos en fosmacore.",
    "createdAt": "2026-04-22T09:06:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "acumulado",
    "campoReporte": "Observaciones levantadas"
  },
  {
    "id": "excel-0007",
    "fecha": "2026-04-23",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 41,
    "grupo": "Primer grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Días 23 de abril, se reemplazaron los reporte de todos los contratos ONCONAVAL salvo 2 haciendo en total 109 reportes actualizados, adicionalmente se realizo la actualización de datos en fosmarcore.",
    "createdAt": "2026-04-23T09:07:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0008",
    "fecha": "2026-04-23",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 15,
    "grupo": "Primer grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Días 23 de abril, se reemplazaron los reporte de todos los contratos ONCONAVAL salvo 2 haciendo en total 109 reportes actualizados, adicionalmente se realizo la actualización de datos en fosmarcore.",
    "createdAt": "2026-04-23T09:08:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0009",
    "fecha": "2026-04-23",
    "tipo": "Levantadas",
    "categoria": "Observaciones levantadas",
    "cantidad": 13,
    "grupo": "Primer grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Días 23 de abril, se reemplazaron los reporte de todos los contratos ONCONAVAL salvo 2 haciendo en total 109 reportes actualizados, adicionalmente se realizo la actualización de datos en fosmarcore.",
    "createdAt": "2026-04-23T09:09:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "acumulado",
    "campoReporte": "Observaciones levantadas"
  },
  {
    "id": "excel-0010",
    "fecha": "2026-04-24",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 48,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 24 de abril, se realizo la subsancaión de los contratos observados los días 21, 22 y 23 así como la correción de los reportes que figuraban con Nro. De contrato 0, adicionalmente, se verifico la información de 48 contratos del plan de salud basico.",
    "createdAt": "2026-04-24T09:10:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0011",
    "fecha": "2026-04-24",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 5,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 24 de abril, se realizo la subsancaión de los contratos observados los días 21, 22 y 23 así como la correción de los reportes que figuraban con Nro. De contrato 0, adicionalmente, se verifico la información de 48 contratos del plan de salud basico.",
    "createdAt": "2026-04-24T09:11:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0012",
    "fecha": "2026-04-24",
    "tipo": "Levantadas",
    "categoria": "Observaciones levantadas",
    "cantidad": 4,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 24 de abril, se realizo la subsancaión de los contratos observados los días 21, 22 y 23 así como la correción de los reportes que figuraban con Nro. De contrato 0, adicionalmente, se verifico la información de 48 contratos del plan de salud basico.",
    "createdAt": "2026-04-24T09:12:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "acumulado",
    "campoReporte": "Observaciones levantadas"
  },
  {
    "id": "excel-0013",
    "fecha": "2026-04-27",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 55,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 27 de abril, se realizo la verificación de los datos en los contratos del plan base y se actualizo la información en fosmarcore.",
    "createdAt": "2026-04-27T09:13:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0014",
    "fecha": "2026-04-27",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 6,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 27 de abril, se realizo la verificación de los datos en los contratos del plan base y se actualizo la información en fosmarcore.",
    "createdAt": "2026-04-27T09:14:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0015",
    "fecha": "2026-04-28",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 90,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 28 de abril, se verificaron los contratos del plan base y actualización de datos en fosmarcore ademas de reemplazar los reportes en 0 del día 24.",
    "createdAt": "2026-04-28T09:15:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0016",
    "fecha": "2026-04-28",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 9,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 28 de abril, se verificaron los contratos del plan base y actualización de datos en fosmarcore ademas de reemplazar los reportes en 0 del día 24.",
    "createdAt": "2026-04-28T09:16:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0017",
    "fecha": "2026-04-29",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 32,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "No se pudieron realizar laborales con reguralidad debido a corte de luz",
    "createdAt": "2026-04-29T09:17:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0018",
    "fecha": "2026-04-30",
    "tipo": "Otros",
    "categoria": "Incidencia / observación",
    "cantidad": 0,
    "grupo": "General",
    "canal": "",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "No se pudieron realizar laborales debido a corte de internet",
    "createdAt": "2026-04-30T11:18:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Incidencia / observación"
  },
  {
    "id": "excel-0019",
    "fecha": "2026-05-01",
    "tipo": "Otros",
    "categoria": "Incidencia / observación",
    "cantidad": 0,
    "grupo": "General",
    "canal": "",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día del trabajador",
    "createdAt": "2026-05-01T11:19:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Incidencia / observación"
  },
  {
    "id": "excel-0020",
    "fecha": "2026-05-04",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 71,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 4 de mayo, se realizo el levantamiento de reportes observados de los días 27 y 28 de mayo, así como la actualización de la información en fosmar core",
    "createdAt": "2026-05-04T09:20:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0021",
    "fecha": "2026-05-04",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 4,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 4 de mayo, se realizo el levantamiento de reportes observados de los días 27 y 28 de mayo, así como la actualización de la información en fosmar core",
    "createdAt": "2026-05-04T09:21:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0022",
    "fecha": "2026-05-05",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 76,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 5 de mayo, se verifico la información de las pólizas del plan de salud basico de primer y segundo grupo así como la actualización de datos en FOSMARCORE",
    "createdAt": "2026-05-05T09:22:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0023",
    "fecha": "2026-05-05",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 2,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 5 de mayo, se verifico la información de las pólizas del plan de salud basico de primer y segundo grupo así como la actualización de datos en FOSMARCORE",
    "createdAt": "2026-05-05T09:23:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0024",
    "fecha": "2026-05-05",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 20,
    "grupo": "Segundo grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 5 de mayo, se verifico la información de las pólizas del plan de salud basico de primer y segundo grupo así como la actualización de datos en FOSMARCORE",
    "createdAt": "2026-05-05T09:24:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0025",
    "fecha": "2026-05-05",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 4,
    "grupo": "Segundo grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 5 de mayo, se verifico la información de las pólizas del plan de salud basico de primer y segundo grupo así como la actualización de datos en FOSMARCORE",
    "createdAt": "2026-05-05T09:25:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0026",
    "fecha": "2026-05-06",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 52,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 6 de mayo se realizo la revisión de pólizas del plan de salud basico asi como la actualización de datos en FOSMARCORE y la digitalización de documentos.",
    "createdAt": "2026-05-06T09:26:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0027",
    "fecha": "2026-05-06",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 13,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 6 de mayo se realizo la revisión de pólizas del plan de salud basico asi como la actualización de datos en FOSMARCORE y la digitalización de documentos.",
    "createdAt": "2026-05-06T09:27:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0028",
    "fecha": "2026-05-06",
    "tipo": "Digitalización",
    "categoria": "Pólizas digitalizadas",
    "cantidad": 17,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 6 de mayo se realizo la revisión de pólizas del plan de salud basico asi como la actualización de datos en FOSMARCORE and la digitalización de documentos.",
    "createdAt": "2026-05-06T09:28:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas digitalizadas"
  },
  {
    "id": "excel-0029",
    "fecha": "2026-05-07",
    "tipo": "Digitalización",
    "categoria": "Pólizas digitalizadas",
    "cantidad": 78,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Trasladado desde Excel - Mayo",
    "createdAt": "2026-05-07T09:29:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas digitalizadas"
  },
  {
    "id": "excel-0030",
    "fecha": "2026-05-11",
    "tipo": "Digitalización",
    "categoria": "Pólizas digitalizadas",
    "cantidad": 45,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 11 de mayo, se realizo la revisión de pólizas del Plan Básico de de Salud del segundo grupo así como su actualización de datos en la plataforma FOSMARCORE",
    "createdAt": "2026-05-11T09:30:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas digitalizadas"
  },
  {
    "id": "excel-0031",
    "fecha": "2026-05-11",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 54,
    "grupo": "Segundo grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 11 de mayo, se realizo la revisión de pólizas del Plan Básico de de Salud del segundo grupo así como su actualización de datos en la plataforma FOSMARCORE",
    "createdAt": "2026-05-11T09:31:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0032",
    "fecha": "2026-05-11",
    "tipo": "Pólizas",
    "categoria": "Pólizas observadas",
    "cantidad": 5,
    "grupo": "Segundo grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Día 11 de mayo, se realizo la revisión de pólizas del Plan Básico de de Salud del segundo grupo así como su actualización de datos en la plataforma FOSMARCORE",
    "createdAt": "2026-05-11T09:32:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas observadas"
  },
  {
    "id": "excel-0033",
    "fecha": "2026-05-12",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 15,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Trasladado desde Excel - Mayo",
    "createdAt": "2026-05-12T09:33:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0034",
    "fecha": "2026-05-12",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 31,
    "grupo": "Segundo grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Trasladado desde Excel - Mayo",
    "createdAt": "2026-05-12T09:34:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  },
  {
    "id": "excel-0035",
    "fecha": "2026-05-13",
    "tipo": "Digitalización",
    "categoria": "Pólizas digitalizadas",
    "cantidad": 54,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Trasladado desde Excel - Mayo",
    "createdAt": "2026-05-13T09:35:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas digitalizadas"
  },
  {
    "id": "excel-0036",
    "fecha": "2026-05-13",
    "tipo": "Digitalización",
    "categoria": "Pólizas digitalizadas",
    "cantidad": 54,
    "grupo": "Primer grupo",
    "canal": "Onconaval",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Trasladado desde Excel - Mayo",
    "createdAt": "2026-05-13T09:36:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas digitalizadas"
  },
  {
    "id": "excel-0037",
    "fecha": "2026-05-14",
    "tipo": "Pólizas",
    "categoria": "Pólizas aprobadas",
    "cantidad": 9,
    "grupo": "Primer grupo",
    "canal": "Plan Básico",
    "responsable": "Sebastián Fernando Mesones Ugolini",
    "observacion": "Se realizo el re-escaneo de los 140 documentos previamente digitalizados, adicionalmente se subasaron los planes observados del diás 4 y 5 de mayo, por ultimo se enviaron los documentos por correo a los afilaidos",
    "createdAt": "2026-05-14T09:37:00.000Z",
    "origen": "Excel trasladado",
    "fechaModo": "diario",
    "campoReporte": "Pólizas aprobadas"
  }
];
